# .github/workflows/ci-tests.yml
name: RAG Chatbot - CI Tests

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main, dev ]

jobs:
  test:
    runs-on: ubuntu-24.04

    # ↓ Give each artifact a predictable ID to avoid clashes across jobs
    env:
      TEST_RESULTS: pytest-report

    steps:
      # -- Checkout ------------------------------------------------------------------
      - name: Check out code
        uses: actions/checkout@v4

      # -- Set up Python -------------------------------------------------------------
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      # -- Install deps --------------------------------------------------------------
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -r requirements-dev.txt

      # -- Run tests -----------------------------------------------------------------
      - name: Run unit + integration tests
        run: |
          pytest -q \
            --junitxml=reports/junit.xml \
            --cov=app --cov-report=xml --cov-report=term

      # -- Upload artifacts (NOTE v4!) ----------------------------------------------
      - name: Upload test results
        if: always()              # Upload even when pytest fails
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.TEST_RESULTS }}
          path: |
            reports/junit.xml
            coverage.xml
          retention-days: 14
