# .github/workflows/ci-tests.yml
name: RAG Chatbot - CI Tests

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main, dev ]

jobs:
  test:
    runs-on: ubuntu-latest

    env:
      TEST_RESULTS: pytest-report

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run unit + integration tests and generate reports
        run: |
          mkdir -p reports
          python -m pytest tests \
            --junitxml=reports/junit.xml \
            --cov=app \
            --cov-report=xml:reports/coverage.xml

      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.TEST_RESULTS }}
          path: |
            reports/junit.xml
            reports/coverage.xml
          retention-days: 14
